name: Build and Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.3

    - name: Build binaries
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o broadcast-linux-amd64 .
      env:
        CGO_ENABLED: 1

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          broadcast-linux-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
