name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.3

    - name: Build binaries
      run: |
        mkdir dist
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/broadcast_linux .
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/broadcast_darwin .
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/broadcast_windows.exe .

    - name: Upload Linux binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: broadcast_linux
        asset_name: broadcast-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload macOS binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/broadcast_darwin
        asset_name: broadcast-darwin-amd64
        asset_content_type: application/octet-stream

    - name: Upload Windows binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/broadcast_windows.exe
        asset_name: broadcast-windows-amd64.exe
        asset_content_type: application/octet-stream
