name: Build and Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
        image: docker.elastic.co/beats-dev/golang-crossbuild:1.22.3-main-debian12

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.3

    - name: Build binaries
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o broadcast-linux-amd64 .
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o broadcast-windows-amd64.exe
      env:
        CGO_ENABLED: 1

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          broadcast-linux-amd64
          broadcast-windows-amd64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
